dist: xenial
language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -e .
script: python -m unittest discover tests/
notifications:
  email: false
  slack:
    secure: AHDGwVG1cdOyixIlDzq8jGH1ScYC40mVwSwyJWfR9+0oSOklna2GuRot++03IXrpx6DLEwWWw9c3d2YB2SVu2820PdhRPAox4gfarVUK1JKOpOEDScLUAZ4dkdG+ZYtptfqW5wdy+TSVX+FXFgJBAb8lZV9ffvwsKq8kfCD8rVFR+dBw86o17AMbltG1wWnUVyVCG/qJpnq6Ri58u5xTWoxbSD+LKKTBY8G+aqofuX1Ic2X55DddYcgKDWqHyZC93qpbhbzfSX/UGxGuJEnndVlylP+CyTOYe0uozQYDT3suM9kd76XxzkKxAFcKZJb+veTNegiDep6Fdu5SvGC2Hn6zATvVzWZFN3575Ax7yST6IrDMskSa671SopmbfYQplZkvlinXKcXzkEia3HnVWA+Bi33zvkZXkaGVPotauV4t8vG26zNNkZ4vejlRa7KKxnvxCu+QrvggrEYlzB1SJHCNk7diMA6Q6GPEE9MO9wMl8kxw19d9CwqLmfYrw8P5jwirvn2OilnLXfuXQk9DHckrSrNtQ+zeL3+QrbJDqvJCZNwjDltD+8+E0ZjQp9uXaeCTzx8qnsGWGa6H1J7IXLuQcKLLieBMMSRl/ZupCsCZpb/wV3HmxaGDZF6V3Q5igFH8iQnoWlzHvqpVD0st+jhAq8MveIXKh2A0cIorat8=
